config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'tops#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create index]
  resource :profile, only: %i[show edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :user_lessons
  has_many :users, :through => :user_lessons
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :user_subjects
  has_many :users, :through => :user_subjects
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :user_lessons
  has_many :lessons, :through => :user_lessons

  has_many :user_subjects
  has_many :subjects, :through => :user_subjects

  validates :login_id, uniqueness: true, presence: true
  validate :login_id_format

  def login_id_format
    unless login_id.match?(/\A(?=.*[0-9])(?=.*[a-zA-Z])[0-9a-zA-Z]+\z/)
      errors.add(:login_id, "は数字とアルファベットの両方を含む必要があります")
    end
  end
  
  validates :user_name, presence: true, length: { maximum: 255 }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  enum role: { general: 0, admin: 1 }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "crypted_password", "id", "id_value", "login_id", "role", "salt", "updated_at", "user_name"]
  end
end

app/models/user_lesson.rb
class UserLesson < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
end

app/models/user_subject.rb
class UserSubject < ApplicationRecord
  belongs_to :user
  belongs_to :subject
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :check_admin
  layout 'admin/layouts/application'
  
  private
  
  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to admin_login_path
  end
  
  def check_admin
    redirect_to root_path, warning: t('defaults.message.not_authorized') unless current_user.admin?
  end
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :check_admin, only: %i[new create]
  layout 'layouts/admin_login'
  
  def new; end
  
  def create
    @user = login(params[:login_id], params[:password])
    if @user
      redirect_to admin_users_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    logout
    redirect_to admin_login_path, success: t('.success')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[edit update show destroy]
  
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show
    @user = User.find(params[:id]).decorate
    @test_results_data = @user.test_results.order(created_at: :asc).pluck(:test_name, :achievement_rate).map.with_index { |(test_name, achievement_rate), index| ["#{test_name} (#{index + 1})", achievement_rate] }
    @test_results_data2 = @user.test_results.pluck(:preparation_time_minutes, :score)
    @average_achievement_rate = @user.average_achievement_rate
    @test_results = TestResult.where(user_id: @user.id).order(created_at: :desc)
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end
  
  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:login_id, :password, :password_confirmation, :user_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]
  before_action :set_lessons, only: [:edit]
  before_action :set_subjects, only: [:edit]
  
  def edit; end
  
  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end
  
  def show; end
  
  private
  
  def set_user
    @user = User.find(current_user.id)
  end

  def set_lessons
    @lessons = Lesson.all
  end

  def set_subjects
    @subjects = Subject.all
  end
  
  def user_params
    params.require(:user).permit(:login_id, :user_name, lesson_ids: [], subject_ids: [])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    
  def new
    @teacher = Teacher.new
    @lessons = Lesson.all
    @subjects = Subject.all
  end
    
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to users_path, success: t('defaults.message.created', item: Teacher.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Teacher.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end
    
  private
    
  def teacher_params
    params.require(:teacher).permit(:user_id, lesson_ids: [], subject_ids: [])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:user_name], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
        
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end
        
  private
        
  def user_params
    params.require(:user).permit(:login_id, :user_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title =  if admin
                    'TimePlanner(管理画面)'
                  else
                    'TimePlanner'
                  end
    
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def active_if(path)
    path == controller_path ? 'active' : ''
  end
end

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2024 Teach Time.</strong>
  All rights reserved.
</footer>

app/views/admin/shared/_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <%= link_to '#', class: "navbar-brand pe-3" do %>
    TeachTime
    <% end %>
  </div>
</header>

app/views/admin/shared/_sidebar.html.erb
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
  <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <div class="d-flex align-items-center gap-0">
              <%= link_to admin_users_path, class: "nav-link #{active_if('admin/users')}" do %>
                <%= t('admin.users.index.title') %>
              <% end %>      
            </div>
          </a>
        </li>

      <hr class="my-3">

      <ul class="nav flex-column mb-auto">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <div class="d-flex align-items-center gap-0">
              <%= link_to t('defaults.logout'), admin_logout_path, class: 'nav-link', data: { turbo_method: :delete } %>
            </div>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="login-box">
  <!-- /.login-logo -->
  <div class="mb-5"></div> 
  <main class="main-content mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient"><%= t('.title') %></h3>
                </div>
                <div class="card-body login-card-body">

                  <%= form_with url: admin_login_path, local: true do |f| %>
                    <%= f.label :login_id, User.human_attribute_name(:login_id) %>
                    <div class="input-group mb-3">
                      <%= f.text_field :login_id, class: 'form-control', placeholder: :login_id %>
                    </div>

                    <%= f.label :password, User.human_attribute_name(:password) %>
                    <div class="input-group mb-3">
                      <%= f.password_field :password, class: 'form-control', placeholder: :password %>
                    </div>

                    <div class="row">
                      <div class="col-12">
                        <%= f.submit (t 'defaults.login'), class: 'text-info text-gradient font-weight-bold' %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/admin/users/_search_form.html.erb
<%= search_form_for @q, url: admin_users_path do |f| %>
  <div class="row">
    <div class="col-auto">
      <%= f.search_field :user_name_cont, class: 'form-control', placeholder: '名前で検索' %>
    </div>
    <div class="col-auto">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.user_name %>
  </td>
  <td>
    <%= l user.created_at, format: :long %>
  </td>
  <td>
    <div class="btn-group" role="group">
      <%= button_to t('defaults.show'), admin_user_path(user), class: 'btn btn-info me-2' %>
      <%= button_to t('defaults.edit'), edit_admin_user_path(user), class: 'btn btn-success me-2' %>
      <%= button_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
    </div>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <h1><%= t '.title' %></h1>
  <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="row">
      <div class="col-sm-6">
        <div class="position-relative mb-4">
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="position-relative mb-4">
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="position-relative mb-4">
          <div class="form-group">
            <%= f.label :nickname %>
            <%= f.text_field :nickname, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="position-relative mb-4">
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="col-12 mb-2">
        <div class="position-relative mb-4">
          <div class="form-group">
            <%= f.label :grade_and_class %>
            <%= f.select :grade_and_class, options_for_select(grade_and_class_options, @user.grade_and_class), {}, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="col-12 mb-4">
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>
      </div>
    </div>
    <%= f.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</main>

app/views/admin/users/index.html.erb
<% content_for(:title, t('.title')) %>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:grade_and_class) %></th>
          <th scope="col"><%= User.human_attribute_name(:full_name) %></th>
          <th scope="col"><%= User.human_attribute_name(:introduction) %></th>
          <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/admin/users/show.html.erb
<% content_for(:title, t('.title')) %>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <h1><%= t('.title') %></h1>
  <div class="text-right mb-3">
    <%= link_to t('defaults.edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_user_path(@user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </div>
  <table class="table table-bordered bg-white">
    <tr>
      <th scope="row"><%= User.human_attribute_name(:id) %></th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th scope="row"><%= User.human_attribute_name(:full_name) %></th>
      <td><%= @user.decorate.full_name %></td>
    </tr>
    <tr>
      <th scope="row"><%= User.human_attribute_name(:nickname) %></th>
      <td><%= @user.nickname %></td>
    </tr>
    <tr>
      <th scope="row"><%= User.human_attribute_name(:grade_and_class)%></th>
      <td><%= @user.grade_and_class %></td>
    </tr>
    <tr>
      <th scope="row"><%= '達成率の平均値'%></th>
      <td><%= @average_achievement_rate.present? ? number_to_percentage(@average_achievement_rate, precision: 0) : 'N/A' %>
    <tr>
    <tr>
      <th scope="row"><%= User.human_attribute_name(:introduction) %></th>
      <td><%= @user.introduction %></td>
    </tr>
    <tr>
      <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
      <td><%= l @user.created_at, format: :long %></td>
    </tr>
  </table>
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 1000px;">
    <div class="row">
      <div class="col-md-6">
        <%= line_chart @test_results_data, xtitle: 'テスト名', ytitle: '達成率', height: '400px' %>
      </div>
      <div class="col-md-6">
        <%= scatter_chart @test_results_data2, xtitle: '学習時間（分）', ytitle: '点数', height: '400px' %>
      </div>
    </div>
  </div>
</main>

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
      <%= form_with model: @user, url: profile_path, local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :login_id %>
        <%= f.text_field :login_id, class: 'form-control mb-3' %>

        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: 'form-control mb-3' %>

        <div class="row">
          <div class="col-md-6">
            <h5>担当クラス</h5>
            <% @lessons.each do |lesson| %>
              <div>
                <%= check_box_tag "user[lesson_ids][]", lesson.id, @user.lessons.include?(lesson), id: "lesson_#{lesson.id}" %>
                <%= lesson.lesson_name %>
              </div>
            <% end %>
          </div>
          <div class="col-md-6">
            <h5>担当教科</h5>
            <% @subjects.each do |subject| %>
              <div>
                <%= check_box_tag "user[subject_ids][]", subject.id, @user.subjects.include?(subject), id: "subject_#{subject.id}" %>
                <%= subject.subject_name %>
              </div>
            <% end %>
          </div>
        </div>

        <%= f.submit class: 'btn btn-primary mt-3 w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
      <table class="table">
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:login_id)) %></th>
          <td><%= current_user.login_id %></td>
        </tr>
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:user_name)) %></th>
          <td><%= current_user.user_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:lesson_name)) %></th>
          <td>
            <% if current_user.lessons.any? %>
              <% current_user.lessons.each do |lesson| %>
                <%= lesson.lesson_name %><br>
              <% end %>
            <% else %>
              <%= '登録されていません' %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row"><%= t(User.human_attribute_name(:subject_name)) %></th>
          <td>
            <% if current_user.subjects.any? %>
              <% current_user.subjects.each do |subject| %>
                <%= subject.subject_name %><br>
              <% end %>
            <% else %>
              <%= '登録されていません' %>
            <% end %>
          </td>
        </tr>
      </table>
      <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right' %>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
        TimePlanner
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to (t 'defaults.login') ,login_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
      </div>      
    </div>
    <%= link_to (t 'defaults.login'), login_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer pt-5 pb-4 pb-lg-5">
  <div class="container pt-lg-4">
    <div class="row pb-5">
      <div class="col-lg-4 col-md-6">
        <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
          <h3>TimePlanner</h3>
        </div>
      </div>
      <div class="col-xl-6 col-lg-7 col-md-5 offset-xl-2 offset-md-1 pt-4 pt-md-1 pt-lg-0">
        <div id="footer-links" class="row">
          <div class="col-lg-4">
            <h6 class="mb-2">
            <a href="#useful-links" class="d-block text-dark dropdown-toggle d-lg-none py-2" data-bs-toggle="collapse">Useful Links</a>
            </h6>
            <div id="useful-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
              <ul class="nav flex-column mb-2 mb-lg-0">
                <li class="nav-item"><a href="#", class="nav-link d-inline-block px-0 pt-1 pb-2">Terms &amp; Conditions</a></li>
                <li class="nav-item"><a href="#", class="nav-link d-inline-block px-0 pt-1 pb-2">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
          <div class="col-xl-4 col-lg-5 pt-2 pt-lg-0">
            <h6 class="mb-2">Contact</h6>
            <a href="https://forms.gle/NaBSGqofxi3guzEAA" target="_blank">お問い合わせはこちらから</a>
          </div>
        </div>
      </div>
    </div>
    <p class="nav d-block fs-xs text-center text-md-start pb-2 pb-lg-0 mb-0">
      &copy; All rights reserved. Made by Shimosako
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- Navbar -->
<!-- Remove "fixed-top" class to make navigation bar scrollable with the page -->
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
      TimePlanner
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to (t 'defaults.logout'), logout_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
      </div>      
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to (t 'profiles.show.title'), profile_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
    </div>
    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to (t 'defaults.logout'), logout_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
    </div>
  </div>
</header>

app/views/teachers/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    
    <%= form_with(model: @teacher, url: teachers_path, local: true) do |form| %>
      <div class="col-12">
        <div class="position-relative mb-4">
          <div class="field">
            <%= form.label :user_id, '名前を選ぶ' %>
            <%= form.select :user_id, User.all.map { |user| [user.user_name, user.id] }, prompt: 'Select User' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 mb-4">
          <div class="field">
            <h5>クラスを選択</h5>
            <%= form.collection_check_boxes :lesson_ids, Lesson.all, :id, :lesson_name do |b| %>
              <%= b.label { b.check_box + b.text } %><br>
            <% end %>
          </div>
        </div>
    
  
        <div class="col-md-6 mb-4">
          <div class="field">
            <h5>科目を選択</h5>
            <%= form.collection_check_boxes :subject_ids, Subject.all, :id, :subject_name do |b| %>
              <%= b.label { b.check_box + b.text } %><br>
            <% end %>
          </div>
        </div>
      </div>

      <div class="actions">
        <%= form.submit (t 'defaults.register'), class: "btn btn-primary shadow-primary btn-lg w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<!-- Sign in form -->
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <%= form_with url: login_path, local: true do |f| %>
      <div class="position-relative mb-4">
        <div class="form-group">
          <%= f.label :login_id, User.human_attribute_name(:login_id) %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
      </div>
      <div class="mb-4">
        <div class="form-group">
          <%= f.label :password, User.human_attribute_name(:password)  %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>
      <div class="actions mb-4">
        <%= f.submit (t 'defaults.login'), class: 'btn btn-primary shadow-primary btn-lg w-100' %>
      </div>
    <% end %>
    <div class='text-center'>
      <%= link_to (t '.to_register_page'), new_user_path %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.user_name %>
  </td>
  <td>
  
  </td>
  <td>
    
  </td>
</tr>